language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database db_development;' -U postgres
  - psql -c 'create database db_test;' -U postgres
  - psql -c 'create database db_production;' -U postgres