language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database db_development;' -U jimnahmagira
  - psql -c 'create database db_test;' -U jimnahmagira
  - psql -c 'create database db_production;' -U jimnahmagira