module.exports =
[{
  id: 1,
  title: 'Helpful Spouse',
  content: 'A man and his wife are having a huge argument when their car is...',
  dateCreated: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  access: 'private',
  userId: '1',
}, {
  id: 2,
  title: 'Top joke in Australia',
  content: 'This woman rushed to see her doctor, looking very much worried and all...',
  dateCreated: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  userId: '2',
  access: 'public',
}, {
  id: 3,
  title: 'Lorem ipsum dolor sit amet',
  content: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ...',
  dateCreated: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  userId: '3',
  access: 'private',
}, {
  id: 4,
  title: 'Li Europan lingues es membres ',
  content: 'At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun ...',
  dateCreated: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  userId: '3',
  access: 'public',
}];
