module.exports = [{
    _id: 1,
    email: 'johndoe@example.com',
    password: 'password',
    firstName: 'John',
    lastName: 'Doe',
    roleId: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
},{
    _id: 2,
    email: 'janedoe@example.com',
    password: 'password',
    firstName: 'Jane',
    lastName: 'Doe',
    roleId: '2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
},
];