module.exports = [{
  id: 1,
  email: 'johndoe@example.com',
  password: 'password',
  username: 'JohnDoe',
  firstName: 'John',
  lastName: 'Doe',
  roleId: 1,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}, {
  id: 2,
  email: 'stuff@email.au',
  username: 'stuff',
  password: 'password',
  firstName: 'Jane',
  lastName: 'Doe',
  roleId: 2,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}, {
  id: 3,
  email: 'test@login.com',
  username: 'testlogin',
  password: 'letmein',
  firstName: 'Test',
  lastName: 'Login',
  roleId: 2,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
},
];
